DROP TABLE IF EXISTS expenses;
CREATE TABLE expenses (
	id				INT AUTO_INCREMENT	NOT NULL,
	name			VARCHAR(255),
	amount			DECIMAL(20,2)		NOT NULL	DEFAULT 0,
	purchased		DATE 				NOT NULL	DEFAULT (CURRENT_DATE()),
	created			DATETIME 			NOT NULL	DEFAULT (CURRENT_DATE()),
	PRIMARY KEY		(`id`)
);

