DROP TABLE IF EXISTS expenses;
CREATE TABLE expenses (
	id				INT AUTO_INCREMENT 	NOT NULL,
	purchased		DATETIME 			NOT NULL	DEFAULT	CURRENT_TIMESTAMP,
	name			VARCHAR(256),
	amount			DECIMAL(20,2)		NOT NULL	DEFAULT 0,
	PRIMARY KEY		(`id`)
);

